export const dummyResponse = [
  {
    SUBJECT: "0",
    AUTHOR: "저자 : 조현영",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "",
    EA_ISBN: "9791165215958",
    PUBLISHER: "(주 도서출판)길벗",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "http://seoji.nl.go.kr/fu/ecip/dbfiles/CIP_FILES_TBL/2021/06/14/9791165215958.jpg",
    PUBLISH_PREDATE: "20210625",
    EA_ADD_CODE: "95000",
    SET_EXPRESSION: "",
    FORM_DETAIL: "EPUB",
    BIB_YN: "N",
    CIP_YN: "N",
    EBOOK_YN: "Y",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210614",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "전자책",
    PRE_PRICE: "17,500",
    PUBLISHER_URL: "http://www.gilbut.co.kr",
    BOOK_SIZE: "",
    DEPOSIT_YN: "N",
    RELATED_ISBN: "9791165215873",
    KDC: "",
    TITLE: "Let’s Get IT 자바스크립트 프로그래밍(ePub)"
  },
  {
    SUBJECT: "0",
    AUTHOR: "조현영 지음",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "20210812",
    EA_ISBN: "9791165215873",
    PUBLISHER: "길벗",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "",
    PUBLISH_PREDATE: "20210625",
    EA_ADD_CODE: "93000",
    SET_EXPRESSION: "",
    FORM_DETAIL: "무선제본",
    BIB_YN: "Y",
    CIP_YN: "N",
    EBOOK_YN: "N",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "544 p.",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210603",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "종이책",
    PRE_PRICE: "25000",
    PUBLISHER_URL: "http://www.gilbut.co.kr",
    BOOK_SIZE: "183*235",
    DEPOSIT_YN: "Y",
    RELATED_ISBN: "",
    KDC: "",
    TITLE: "(Let's get IT) 자바스크립트 프로그래밍"
  },
  {
    SUBJECT: "0",
    AUTHOR: "곽문기,하호진 지음",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "20210805",
    EA_ISBN: "9788927747680",
    PUBLISHER: "다락원",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "",
    PUBLISH_PREDATE: "20210628",
    EA_ADD_CODE: "93000",
    SET_EXPRESSION: "",
    FORM_DETAIL: "무선제본",
    BIB_YN: "Y",
    CIP_YN: "N",
    EBOOK_YN: "N",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "446 p.",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210528",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "종이책",
    PRE_PRICE: "23000",
    PUBLISHER_URL: "http://www.darakwon.co.kr",
    BOOK_SIZE: "188*235",
    DEPOSIT_YN: "Y",
    RELATED_ISBN: "",
    KDC: "",
    TITLE: "오늘부터 자바스크립트"
  },
  {
    SUBJECT: "0",
    AUTHOR: "저자 : 알베르토 몬탈레시;역자 : 임지순 ;역자 : 권영재;",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "",
    EA_ISBN: "9791162246818",
    PUBLISHER: "한빛미디어(주)",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "http://seoji.nl.go.kr/fu/ecip/dbfiles/CIP_FILES_TBL/2021/05/21/9791162246818.jpg",
    PUBLISH_PREDATE: "20210531",
    EA_ADD_CODE: "95000",
    SET_EXPRESSION: "",
    FORM_DETAIL: "PDF",
    BIB_YN: "N",
    CIP_YN: "N",
    EBOOK_YN: "Y",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210521",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "전자책",
    PRE_PRICE: "15,800",
    PUBLISHER_URL: "http://www.hanbit.co.kr",
    BOOK_SIZE: "",
    DEPOSIT_YN: "N",
    RELATED_ISBN: "",
    KDC: "",
    TITLE: "모던 자바스크립트 핵심 가이드"
  },
  {
    SUBJECT: "0",
    AUTHOR: "알베르토 몬탈레시 지음 ;임지순,권영재 옮김",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "20210728",
    EA_ISBN: "9791162244289",
    PUBLISHER: "한빛미디어",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "",
    PUBLISH_PREDATE: "20210514",
    EA_ADD_CODE: "93000",
    SET_EXPRESSION: "",
    FORM_DETAIL: "무선제본",
    BIB_YN: "Y",
    CIP_YN: "N",
    EBOOK_YN: "N",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "284 p.",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210503",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "종이책",
    PRE_PRICE: "19800",
    PUBLISHER_URL: "http://www.hanbit.co.kr",
    BOOK_SIZE: "153*223",
    DEPOSIT_YN: "Y",
    RELATED_ISBN: "",
    KDC: "",
    TITLE: "모던 자바스크립트 핵심 가이드"
  },
  {
    SUBJECT: "0",
    AUTHOR: "마레인 하버비케 지음 ;양정열 옮김",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "20210504",
    EA_ISBN: "9791161755021",
    PUBLISHER: "에이콘(에이콘출판주식회사)",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "http://seoji.nl.go.kr/fu/ecip/dbfiles/CIP_FILES_TBL/2021/03/26/9791161755021.jpg",
    PUBLISH_PREDATE: "20210331",
    EA_ADD_CODE: "93000",
    SET_EXPRESSION: "",
    FORM_DETAIL: "무선제본",
    BIB_YN: "Y",
    CIP_YN: "N",
    EBOOK_YN: "N",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "567 p.",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210326",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "종이책",
    PRE_PRICE: "33000",
    PUBLISHER_URL: "www.acornpub.co.kr",
    BOOK_SIZE: "188*235",
    DEPOSIT_YN: "Y",
    RELATED_ISBN: "",
    KDC: "",
    TITLE: "자바스크립트 스킬업 3/e"
  },
  {
    SUBJECT: "0",
    AUTHOR: "저자 : 이케다 야스노부;저자 : 카노 타케시;역자 : 이춘혁;",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "",
    EA_ISBN: "9791190665919",
    PUBLISHER: "(주식회사)제이펍",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "http://seoji.nl.go.kr/fu/ecip/dbfiles/CIP_FILES_TBL/2021/03/23/9791190665919.jpg",
    PUBLISH_PREDATE: "20210410",
    EA_ADD_CODE: "95000",
    SET_EXPRESSION: "",
    FORM_DETAIL: "PDF",
    BIB_YN: "N",
    CIP_YN: "N",
    EBOOK_YN: "Y",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210323",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "전자책",
    PRE_PRICE: "23,800",
    PUBLISHER_URL: "http://www.jpub.kr",
    BOOK_SIZE: "",
    DEPOSIT_YN: "N",
    RELATED_ISBN: "9791190665414",
    KDC: "",
    TITLE: "(실무에 바로 적용하는) 자바스크립트 코드 레시피 278"
  },
  {
    SUBJECT: "0",
    AUTHOR: "박경배 지음",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "20210401",
    EA_ISBN: "9788984689053",
    PUBLISHER: "21세기사",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "",
    PUBLISH_PREDATE: "20210302",
    EA_ADD_CODE: "93000",
    SET_EXPRESSION: "",
    FORM_DETAIL: "무선제본",
    BIB_YN: "Y",
    CIP_YN: "N",
    EBOOK_YN: "N",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "371 p.",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210219",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "종이책",
    PRE_PRICE: "30000",
    PUBLISHER_URL: "www.21cbook.co.kr",
    BOOK_SIZE: "210*250",
    DEPOSIT_YN: "Y",
    RELATED_ISBN: "",
    KDC: "",
    TITLE: "HTML5 중심의 CSS3와 자바스크립트"
  },
  {
    SUBJECT: "0",
    AUTHOR: "저자 : 애덤 스콧;역자 : 임지순;",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "",
    EA_ISBN: "9791162247150",
    PUBLISHER: "한빛미디어(주)",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "http://seoji.nl.go.kr/fu/ecip/dbfiles/CIP_FILES_TBL/2021/01/27/9791162247150.jpg",
    PUBLISH_PREDATE: "20210201",
    EA_ADD_CODE: "95000",
    SET_EXPRESSION: "",
    FORM_DETAIL: "PDF",
    BIB_YN: "N",
    CIP_YN: "N",
    EBOOK_YN: "Y",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210127",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "전자책",
    PRE_PRICE: "24,000",
    PUBLISHER_URL: "http://www.hanbit.co.kr",
    BOOK_SIZE: "",
    DEPOSIT_YN: "N",
    RELATED_ISBN: "",
    KDC: "",
    TITLE: "자바스크립트는 모든 곳에 존재한다"
  },
  {
    SUBJECT: "5",
    AUTHOR: "저자 : 김은영;저자 : 이기성;",
    REAL_PUBLISH_DATE: "",
    UPDATE_DATE: "",
    EA_ISBN: "9788931546606",
    PUBLISHER: "(주)성안당",
    SET_ADD_CODE: "",
    SERIES_NO: "",
    TITLE_URL: "",
    PUBLISH_PREDATE: "20000922",
    EA_ADD_CODE: "13570",
    SET_EXPRESSION: "",
    FORM_DETAIL: "무선제본",
    BIB_YN: "N",
    CIP_YN: "N",
    EBOOK_YN: "N",
    SET_ISBN: "",
    DDC: "",
    BOOK_SUMMARY_URL: "",
    SERIES_TITLE: "",
    BOOK_INTRODUCTION_URL: "",
    PAGE: "364",
    EDITION_STMT: "",
    CONTROL_NO: "",
    INPUT_DATE: "20210120",
    REAL_PRICE: "",
    BOOK_TB_CNT_URL: "",
    VOL: "",
    FORM: "종이책",
    PRE_PRICE: "14,000",
    PUBLISHER_URL: "http://www.cyber.co.kr",
    BOOK_SIZE: "148*210",
    DEPOSIT_YN: "N",
    RELATED_ISBN: "",
    KDC: "",
    TITLE: "자바스크립트/VB스크립트"
  }
];
